db:
  image: mysql:5.7
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: image_stock
  # command: mysqld --default-authentication-plugin=mysql_native_password
  # --skip-mysqlx
web:
  build: .
  command: puma
  container_name: image_stock
  ports:
    - "7001:3000"
  links:
    - db
  volumes:
    - .:/image_stock